package com.daijie.ksyllabusapp.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.daijie.ksyllabusapp.repository.lesson.LessonRecord;
import com.daijie.ksyllabusapp.repository.lesson.ShareLessonRecord;
import com.daijie.ksyllabusapp.repository.lessonrule.LessonRuleRecord;

import com.daijie.ksyllabusapp.greendao.LessonRecordDao;
import com.daijie.ksyllabusapp.greendao.ShareLessonRecordDao;
import com.daijie.ksyllabusapp.greendao.LessonRuleRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lessonRecordDaoConfig;
    private final DaoConfig shareLessonRecordDaoConfig;
    private final DaoConfig lessonRuleRecordDaoConfig;

    private final LessonRecordDao lessonRecordDao;
    private final ShareLessonRecordDao shareLessonRecordDao;
    private final LessonRuleRecordDao lessonRuleRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lessonRecordDaoConfig = daoConfigMap.get(LessonRecordDao.class).clone();
        lessonRecordDaoConfig.initIdentityScope(type);

        shareLessonRecordDaoConfig = daoConfigMap.get(ShareLessonRecordDao.class).clone();
        shareLessonRecordDaoConfig.initIdentityScope(type);

        lessonRuleRecordDaoConfig = daoConfigMap.get(LessonRuleRecordDao.class).clone();
        lessonRuleRecordDaoConfig.initIdentityScope(type);

        lessonRecordDao = new LessonRecordDao(lessonRecordDaoConfig, this);
        shareLessonRecordDao = new ShareLessonRecordDao(shareLessonRecordDaoConfig, this);
        lessonRuleRecordDao = new LessonRuleRecordDao(lessonRuleRecordDaoConfig, this);

        registerDao(LessonRecord.class, lessonRecordDao);
        registerDao(ShareLessonRecord.class, shareLessonRecordDao);
        registerDao(LessonRuleRecord.class, lessonRuleRecordDao);
    }
    
    public void clear() {
        lessonRecordDaoConfig.clearIdentityScope();
        shareLessonRecordDaoConfig.clearIdentityScope();
        lessonRuleRecordDaoConfig.clearIdentityScope();
    }

    public LessonRecordDao getLessonRecordDao() {
        return lessonRecordDao;
    }

    public ShareLessonRecordDao getShareLessonRecordDao() {
        return shareLessonRecordDao;
    }

    public LessonRuleRecordDao getLessonRuleRecordDao() {
        return lessonRuleRecordDao;
    }

}
