package com.daijie.ksyllabusapp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.daijie.ksyllabusapp.repository.lesson.LessonRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LESSON_RECORD".
*/
public class LessonRecordDao extends AbstractDao<LessonRecord, Long> {

    public static final String TABLENAME = "LESSON_RECORD";

    /**
     * Properties of entity LessonRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LessonsJson = new Property(1, String.class, "lessonsJson", false, "LESSONS_JSON");
        public final static Property Account = new Property(2, String.class, "account", false, "ACCOUNT");
        public final static Property SemesterYear = new Property(3, int.class, "semesterYear", false, "SEMESTER_YEAR");
        public final static Property SemesterSeason = new Property(4, int.class, "semesterSeason", false, "SEMESTER_SEASON");
    }


    public LessonRecordDao(DaoConfig config) {
        super(config);
    }
    
    public LessonRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LESSON_RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LESSONS_JSON\" TEXT," + // 1: lessonsJson
                "\"ACCOUNT\" TEXT," + // 2: account
                "\"SEMESTER_YEAR\" INTEGER NOT NULL ," + // 3: semesterYear
                "\"SEMESTER_SEASON\" INTEGER NOT NULL );"); // 4: semesterSeason
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_LESSON_RECORD_ACCOUNT ON \"LESSON_RECORD\"" +
                " (\"ACCOUNT\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_LESSON_RECORD_SEMESTER_YEAR ON \"LESSON_RECORD\"" +
                " (\"SEMESTER_YEAR\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_LESSON_RECORD_SEMESTER_SEASON ON \"LESSON_RECORD\"" +
                " (\"SEMESTER_SEASON\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LESSON_RECORD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LessonRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lessonsJson = entity.getLessonsJson();
        if (lessonsJson != null) {
            stmt.bindString(2, lessonsJson);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(3, account);
        }
        stmt.bindLong(4, entity.getSemesterYear());
        stmt.bindLong(5, entity.getSemesterSeason());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LessonRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String lessonsJson = entity.getLessonsJson();
        if (lessonsJson != null) {
            stmt.bindString(2, lessonsJson);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(3, account);
        }
        stmt.bindLong(4, entity.getSemesterYear());
        stmt.bindLong(5, entity.getSemesterSeason());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LessonRecord readEntity(Cursor cursor, int offset) {
        LessonRecord entity = new LessonRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // lessonsJson
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // account
            cursor.getInt(offset + 3), // semesterYear
            cursor.getInt(offset + 4) // semesterSeason
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LessonRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLessonsJson(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAccount(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSemesterYear(cursor.getInt(offset + 3));
        entity.setSemesterSeason(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LessonRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LessonRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LessonRecord entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
